services:
    sis-student:
        container_name: sis-student
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - sis_student_network
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.sis-student.rule=Host(`student.sis.uz`)"
            - "traefik.http.routers.sis-student.entrypoints=websecure"
            - "traefik.http.routers.sis-student.tls=true"
            - "traefik.http.routers.sis-student-http.rule=Host(`student.sis.uz`)"
            - "traefik.http.routers.sis-student-http.entrypoints=web"
            - "traefik.http.routers.sis-student-http.middlewares=sis-student-https"
            - "traefik.http.middlewares.sis-student-https.redirectscheme.scheme=https"
            - "traefik.http.services.sis-student.loadbalancer.server.port=80"
networks:
    sis_student_network:
        name: production_network
        external: true
